services:
  api:
    build: ./backend
    volumes:
      - ./sources:/app/sources
      - ./media:/app/media
      - ./data:/app/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./media:/media:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
